# Generated by Django 3.2.13 on 2022-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_click',
            field=models.IntegerField(default=0),
        ),
    ]
