# Generated by Django 3.2.13 on 2022-11-19 05:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20221118_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bad_user',
        ),
        migrations.AddField(
            model_name='review',
            name='bad_user',
            field=models.ManyToManyField(related_name='bad_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='review',
            name='good_user',
        ),
        migrations.AddField(
            model_name='review',
            name='good_user',
            field=models.ManyToManyField(related_name='good_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
