# Generated by Django 3.2.13 on 2022-11-19 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_review_wish_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='wish_user',
        ),
        migrations.AddField(
            model_name='movie',
            name='wish_user',
            field=models.ManyToManyField(related_name='wish_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
