# Generated by Django 3.2.13 on 2022-11-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20221119_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='wish_user',
        ),
    ]
