# Generated by Django 3.2.13 on 2022-11-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
