# Generated by Django 3.2.13 on 2022-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_path',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
